/lslidar_driver_node:
  ros__parameters: 
    lidar_name: N10P
    serial_port: /dev/ttyCH343USB0
    frame_id: laser                                      
    topic: 
      open_scan: true
      scan: /scan
      open_point_cloud2: true
      point_cloud2: /lslidar_point_cloud2 
    angle_range: [0.0, 120.0, 140.0, 360.0] # 角度裁剪(开始,结束,开始,结束)
    distance_range: [10.0, 120.0, 130.0, 200.0] # 距离裁剪[厘米](开始,结束,开始,结束)
