/lslidar_driver_node_2:
  ros__parameters: 
    lidar_name: N10P_2
    serial_port: /dev/ttyACM1
    frame_id: laser_2                                      
    topic: 
      open_scan: true
      scan: /scan
      open_point_cloud2: true
      point_cloud2: /lslidar_point_cloud2 
    angle_range: [0.0, 360.0] # 角度裁剪(开始,结束)
    distance_range: [10.0, 200.0] # 距离裁剪[厘米](开始,结束)
